class ListScreenVM

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ Row delegate
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  function onRowWillEnter(index, direction)
    ? "onRowWillEnter (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onRowWillExit(index, direction)
    ? "onRowWillExit (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onRowDidEnter(index, direction)
    ? "onRowDidEnter (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onRowDidExit(index, direction)
    ? "onRowDidExit (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onRowWillGainFocus(index, direction)
    ? "onRowWillGainFocus (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onRowWillLoseFocus(index, direction)
    ? "onRowWillLoseFocus (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onRowDidGainFocus(index, direction)
    ? "onRowDidGainFocus (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onRowDidLoseFocus(index, direction)
    ? "onRowDidLoseFocus (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onRowGainingFocus(index, direction, fraction)
    ? "onRowGainingFocus (index: " ; index ; " direction: " ; direction ; ", % " ; fraction ; ")"
  end function

  function onRowLosingFocus(index, direction, fraction)
    ? "onRowLosingFocus (index: " ; index ; " direction: " ; direction ; ", % " ; fraction ; ")"
  end function


end class