class ListScreenVM

  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  '++ delegate
  '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  function onWillEnter(index, direction)
    ? "onWillEnter (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onWillExit(index, direction)
    ? "onWillExit (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onDidEnter(index, direction)
    ? "onDidEnter (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onDidExit(index, direction)
    ? "onDidExit (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onWillGainFocus(index, direction)
    ? "onWillGainFocus (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onWillLoseFocus(index, direction)
    ? "onWillLoseFocus (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onDidGainFocus(index, direction)
    ? "onDidGainFocus (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onDidLoseFocus(index, direction)
    ? "onDidLoseFocus (index: " ; index ; " direction: " ; direction ; ")"
  end function

  function onGainingFocus(index, direction, fraction)
    ? "onGainingFocus (index: " ; index ; " direction: " ; direction ; ", % " ; fraction ; ")"
  end function

  function onLosingFocus(index, direction, fraction)
    ? "onLosingFocus (index: " ; index ; " direction: " ; direction ; ", % " ; fraction ; ")"
  end function


end class